// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NumberGeneratorService.proto

package com.example;

/**
 * Protobuf type {@code NumberGeneratorRequest}
 */
public  final class NumberGeneratorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NumberGeneratorRequest)
    NumberGeneratorRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NumberGeneratorRequest.newBuilder() to construct.
  private NumberGeneratorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NumberGeneratorRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NumberGeneratorRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NumberGeneratorRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            firstValue_ = input.readInt32();
            break;
          }
          case 16: {

            lastValue_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.NumberGeneratorProto.internal_static_NumberGeneratorRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.NumberGeneratorProto.internal_static_NumberGeneratorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.NumberGeneratorRequest.class, com.example.NumberGeneratorRequest.Builder.class);
  }

  public static final int FIRSTVALUE_FIELD_NUMBER = 1;
  private int firstValue_;
  /**
   * <code>int32 firstValue = 1;</code>
   */
  public int getFirstValue() {
    return firstValue_;
  }

  public static final int LASTVALUE_FIELD_NUMBER = 2;
  private int lastValue_;
  /**
   * <code>int32 lastValue = 2;</code>
   */
  public int getLastValue() {
    return lastValue_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (firstValue_ != 0) {
      output.writeInt32(1, firstValue_);
    }
    if (lastValue_ != 0) {
      output.writeInt32(2, lastValue_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (firstValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, firstValue_);
    }
    if (lastValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, lastValue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.NumberGeneratorRequest)) {
      return super.equals(obj);
    }
    com.example.NumberGeneratorRequest other = (com.example.NumberGeneratorRequest) obj;

    if (getFirstValue()
        != other.getFirstValue()) return false;
    if (getLastValue()
        != other.getLastValue()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIRSTVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getFirstValue();
    hash = (37 * hash) + LASTVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getLastValue();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.NumberGeneratorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.NumberGeneratorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.NumberGeneratorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.NumberGeneratorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.NumberGeneratorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.NumberGeneratorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.NumberGeneratorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.NumberGeneratorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.NumberGeneratorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.NumberGeneratorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.NumberGeneratorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.NumberGeneratorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.NumberGeneratorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NumberGeneratorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NumberGeneratorRequest)
      com.example.NumberGeneratorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.NumberGeneratorProto.internal_static_NumberGeneratorRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.NumberGeneratorProto.internal_static_NumberGeneratorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.NumberGeneratorRequest.class, com.example.NumberGeneratorRequest.Builder.class);
    }

    // Construct using com.example.NumberGeneratorRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      firstValue_ = 0;

      lastValue_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.NumberGeneratorProto.internal_static_NumberGeneratorRequest_descriptor;
    }

    @java.lang.Override
    public com.example.NumberGeneratorRequest getDefaultInstanceForType() {
      return com.example.NumberGeneratorRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.NumberGeneratorRequest build() {
      com.example.NumberGeneratorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.NumberGeneratorRequest buildPartial() {
      com.example.NumberGeneratorRequest result = new com.example.NumberGeneratorRequest(this);
      result.firstValue_ = firstValue_;
      result.lastValue_ = lastValue_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.NumberGeneratorRequest) {
        return mergeFrom((com.example.NumberGeneratorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.NumberGeneratorRequest other) {
      if (other == com.example.NumberGeneratorRequest.getDefaultInstance()) return this;
      if (other.getFirstValue() != 0) {
        setFirstValue(other.getFirstValue());
      }
      if (other.getLastValue() != 0) {
        setLastValue(other.getLastValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.NumberGeneratorRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.NumberGeneratorRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int firstValue_ ;
    /**
     * <code>int32 firstValue = 1;</code>
     */
    public int getFirstValue() {
      return firstValue_;
    }
    /**
     * <code>int32 firstValue = 1;</code>
     */
    public Builder setFirstValue(int value) {
      
      firstValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 firstValue = 1;</code>
     */
    public Builder clearFirstValue() {
      
      firstValue_ = 0;
      onChanged();
      return this;
    }

    private int lastValue_ ;
    /**
     * <code>int32 lastValue = 2;</code>
     */
    public int getLastValue() {
      return lastValue_;
    }
    /**
     * <code>int32 lastValue = 2;</code>
     */
    public Builder setLastValue(int value) {
      
      lastValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lastValue = 2;</code>
     */
    public Builder clearLastValue() {
      
      lastValue_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NumberGeneratorRequest)
  }

  // @@protoc_insertion_point(class_scope:NumberGeneratorRequest)
  private static final com.example.NumberGeneratorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.NumberGeneratorRequest();
  }

  public static com.example.NumberGeneratorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NumberGeneratorRequest>
      PARSER = new com.google.protobuf.AbstractParser<NumberGeneratorRequest>() {
    @java.lang.Override
    public NumberGeneratorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NumberGeneratorRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NumberGeneratorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NumberGeneratorRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.NumberGeneratorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

